### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by alankilborn** [ThosRTanner/Docking_Dialogue_Interface#2] opened 2023-12-23 13:24 UTC
Using Visual Studio 2022 Community Edition, I get a lot of build errors of this type:

```
Build started...
1>------ Build started: Project: DialogueDemo, Configuration: Debug x64 ------
1>Demo_Plugin.cpp
1>Goto_Dialogue.cpp
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2721,10): error C2467: illegal declaration of anonymous 'struct' (compiling source file demo\Demo_Plugin.cpp)
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(13773,10): error C2467: illegal declaration of anonymous 'struct' (compiling source file demo\Demo_Plugin.cpp)
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(19956,6): error C2467: illegal declaration of anonymous 'struct' (compiling source file demo\Demo_Plugin.cpp)
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(22197,24): error C2133: '_IMAGE_POLICY_METADATA::Policies': unknown size (compiling source file demo\Demo_Plugin.cpp)
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2721,10): error C2467: illegal declaration of anonymous 'struct' (compiling source file demo\Goto_Dialogue.cpp)
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(13773,10): error C2467: illegal declaration of anonymous 'struct' (compiling source file demo\Goto_Dialogue.cpp)
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(19956,6): error C2467: illegal declaration of anonymous 'struct' (compiling source file demo\Goto_Dialogue.cpp)
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(22197,24): error C2133: '_IMAGE_POLICY_METADATA::Policies': unknown size (compiling source file demo\Goto_Dialogue.cpp)
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winioctl.h(4462,10): error C2467: illegal declaration of anonymous 'struct' (compiling source file demo\Goto_Dialogue.cpp)
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winioctl.h(4462,10): error C2467: illegal declaration of anonymous 'struct' (compiling source file demo\Demo_Plugin.cpp)```
```

There's more, but they're mostly all like that.

Should I use a different SDK version?  Which one?  And shouldn't something like that be "baked in" to the project, i.e., if you need a certain version-or-later, shouldn't the project stop trying to build and tell you that?

**Comment by ThosRTanner** [comment] 2023-12-24 07:47
Hmm. I'm using vs2022 community edition and don't see that.

On the other hand, it appears my files are coming from 10.0.22621.0.

I'm rather inclined to blame M/S for this as their default  version seems to be 'latest available'.

Let me see if I can get hold of 10.0.22000.0 and reproduce

**Comment by ThosRTanner** [comment] 2023-12-24 09:07
Right. It appears that prior to 10.0.22621.0 MS uses non-standard language extensions in its header files. Either set Project=>Properties=>Configuration Properties=>C/C++=>Language=>Disable Language Extensions to 'No' or build with the latest SDK version.

I shall update the Readme.md with that information.

Thanks for the feedback.

**Comment by ThosRTanner** [comment] 2023-12-25 18:10
Am closing this now. Instructions have been updated to cover the situation.

**Closed as completed by ThosRTanner** 2023-12-25 18:10 UTC
